export const AUTHORIZATION : string ='/'
export const NOT_EXIST : string ='/404'
export const REGISTRATION : string ='/registration'
export const REGISTRATION_FORGOT_PASSWORD : string ='/registration_forgot_password'
export const REGISTRATION_RESTORE_ACCOUNT : string ='/registration_restore_account'
export const SUCCESSFUL_ACTIVATION : string ='/successful_activation'
export const SUCCESSFUL_CHANGE_EMAIL : string ='/successful_change_email'
export const SUCCESSFUL_SENT_MESSSAGE : string ='/successful_sent_message'